name: Docker Image Release CI

on:
  push:
    tags:
      - 'v*.*.*-rc*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build and push the Docker image
      env:
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
      run: |
        REPO_NAME=${{ github.repository }}
        REPO_LOWERCASE=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
        docker build . --file Dockerfile --tag ghcr.io/$REPO_LOWERCASE:$RELEASE_VERSION
        echo $GHCR_TOKEN | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        docker push ghcr.io/$REPO_LOWERCASE:$RELEASE_VERSION
