name: Docker Image Release CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push the Docker image
      env:
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      run: |
        REPO_NAME=${{ github.repository }}
        REPO_LOWERCASE=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
        DATE=$(date +%s)
        docker build . --file Dockerfile --tag ghcr.io/$REPO_LOWERCASE:$DATE
        docker tag ghcr.io/$REPO_LOWERCASE:$DATE ghcr.io/$REPO_LOWERCASE:latest
        echo $GHCR_TOKEN | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        docker push ghcr.io/$REPO_LOWERCASE:$DATE
        docker push ghcr.io/$REPO_LOWERCASE:latest
