name: Docker Image CI

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Extract repository name
      run: |
        REPO_NAME=${{ github.repository }}
        REPO_LOWERCASE=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
    - name: Build and push the Docker image
      env:
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      run: |
        docker build . --file Dockerfile --tag hellosocket:$(date +%s)
        echo $GHCR_TOKEN | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        echo docker push ghcr.io/$REPO_LOWERCASE:latest
        docker push ghcr.io/$REPO_LOWERCASE:latest
