name: Docker Image Release CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push the Docker image
      env:
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        GITHUB_REF: ${{ env.GITHUB_REF }}
      run: |
        REPO_NAME=${{ github.repository }}
        REPO_LOWERCASE=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
        RELEASE_VERSION=${GITHUB_REF#refs/*/}
        docker build . --file Dockerfile --tag ghcr.io/$REPO_LOWERCASE:$RELEASE_VERSION
        docker tag ghcr.io/$REPO_LOWERCASE:$RELEASE_VERSION ghcr.io/$REPO_LOWERCASE:latest
        echo $GHCR_TOKEN | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        docker push ghcr.io/$REPO_LOWERCASE:$RELEASE_VERSION
        docker push ghcr.io/$REPO_LOWERCASE:latest

  update-deployment:

    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Connect to k8s cluster and update deployment image
      env:
        KUBECONFIG_FULL: ${{ secrets.KUBECONFIG_FULL }}
        GITHUB_REF: ${{ env.GITHUB_REF }}
      run: |
        mkdir .kube
        echo "$KUBECONFIG_FULL" >> .kube/config
        RELEASE_VERSION=${GITHUB_REF#refs/*/}
        kubectl --kubeconfig=.kube/config set image deployment/hellosocket-deployment hellosocket=ghcr.io/bomfunk/hellosocket:$RELEASE_VERSION
