name: Check PEP8

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check PEP8
      run: docker run --rm -v ./:/code eeacms/pep8
